static-analysis-v1 (#325)
Summary:

- AOT analysis of providers using `any-sdk` CLI.
- Pinned stable `go` version.

re run

Corrected AOT analysis working dir.

static-analysis-v1-0-1

static-analysis-v1-0-2

diff --git a/.github/workflows/aot.yml b/.github/workflows/aot.yml
--- a/.github/workflows/aot.yml
+++ b/.github/workflows/aot.yml
@@ -112,18 +112,28 @@ jobs:
             } >> $GITHUB_ENV
           fi
 
-      - name: Run any-sdk cli mocked testing
+      - name: Run any-sdk cli AOT provider analysis
         run: |
           rc='0'
-          for subdir in ./providers/src/*/ ; do
-              echo "Processing provider subdirectory: $subdir" 1>&2
-              # Add commands to execute within each subdirectory here
-              ${{ github.workspace }}/stackql-any-sdk/build/anysdk aot ./providers "${subdir}/v00.00.00000/provider.yaml"
+          for sd in ./providers/src/*/ ; do
+              echo ""
+              subdir="$(realpath "${sd}")"
+              providerID="$(basename "${subdir}")"
+              echo "Processing provider '${providerID}' at subdirectory: '${subdir}'" 1>&2
+              echo ""
+              ${{ github.workspace }}/stackql-any-sdk/build/anysdk aot ./providers "${subdir}/v00.00.00000/provider.yaml" -v
+              echo ""
               if [ "$?" -ne "0" ]; then
+                echo "AOT analysis failed for provider: '${providerID}'" 1>&2
                 rc='1'
+              else
+                echo "AOT analysis succeeded for provider: '${providerID}'" 1>&2
               fi
           done
+          echo ""
           if [ "$rc" -ne "0" ]; then
-            echo "AnySDK AOT build failed"
+            echo "overall anysdk CLI AOT provider analysis failed" 1>&2
             exit 1
+          else
+            echo "overall anysdk CLI AOT provider analysis succeeded" 1>&2
           fi
